name: Kubernetes Deploy
pool:
  vmImage: "ubuntu-20.04"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodApi/*

variables:
  dockerReg: "conDockerReg"
  imageName: "foodapi"
  acr: "integrationsonline.azurecr.io"
  tag: "$(Build.BuildId)"
  kube: "conKube"
  ns: "default"
  imagePullSecret: "secret"

stages:
  - stage: "BuildApi"
    displayName: "Build Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerReg)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: FoodApi/dockerfile
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(dockerReg)
          - publish: "$(Build.SourcesDirectory)/manifests"
            artifact: manifests

  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        displayName: Deploy Job
        environment: "dev.default"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: createSecret
                    secretName: $(imagePullSecret)
                    dockerRegistryEndpoint: $(dockerReg)
                    kubernetesServiceConnection: $(kube)
                    namespace: $(ns)

                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: "deploy"
                    kubernetesServiceConnection: $(kube)
                    manifests: |
                      $(Pipeline.Workspace)/manifests/foodservice.yml
                    imagePullSecrets: $(imagePullSecret)
                    containers: "$(acr)/$(imageName):$(tag)"
