trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodUI
stages:
  - stage: default

    jobs:
      - job: Job
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "12.x"
            displayName: "Install Node.js"

          - script: |
              cd FoodUI
              npm install -g @angular/cli
              npm install
              ng build --prod
            displayName: "npm install and build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "dist/FoodUI"
              ArtifactName: "ngapp"
              publishLocation: "Container"
            displayName: "Publish Artifacts"
