name: variables scopes and jobs
variables:
  global_var: current-value # this is available to all jobs
  changing_var: original-value

stages:
  - stage: Change
    jobs:
      - job: changing_job
        pool:
          vmImage: "ubuntu-20.04"
        variables:
          job_variable1: value1 # this is only available in job1
        steps:
          - bash: echo $(global_var)
          - bash: echo $(job_variable1)
          - bash: echo $JOB_VARIABLE1 # variables are available in the script environment too
          - bash: echo $(changing_var)
          - bash: |
              echo "##vso[task.setvariable variable=changing_var;]changed-value"
            displayName: Changing Value
          - bash: echo $(changing_var)
          - bash: echo ${{ variables.changing_var }}

  - stage: Consume
    jobs:
      - job: consuming_job
        pool:
          vmImage: "ubuntu-20.04"
        variables:
          job_variable2: value2 # this is only available in job2
        steps:
          - bash: echo $(global_var)
          - bash: echo $(job_variable2)
          - bash: echo $GLOBAL_VAR
          - bash: echo $(changing_var)
          - bash: echo ${{ variables.changing_var }}
