name: api build

# trigger:
#   branches:
#     include:
#       - master
#   flds:
#     include:
#       - apps/config-api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  fld: apps/config-api/

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        displayName: "Build Api"

        steps:
          - task: UseDotNet@2
            displayName: "Install .NET 6 SDK"
            inputs:
              packageType: "sdk"
              version: "6.x"

          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(fld)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(fld)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "$(fld)/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          - task: PublishPipelineArtifact@1
            inputs:
              targetfld: '$(Pipeline.Workspace)'
              artifact: 'drop'
              publishLocation: 'pipeline'
