name: api sonarcloud

trigger: none
pr: 
  paths:
    include:
    - apps/config-api/*

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: "Release"
  app: apps/config-api/
  con: scSonar
  org: arambazamba
  projKey: arambazamba_ci-cd-basics
  projName: ci-cd-basics


pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
    inputs:
      version: "$(dotnetSdkVersion)"
  
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: 4.4.1

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: $(con)
      organization: $(org)
      scannerMode: 'MSBuild'
      projectKey: $(projKey)
      projectName: $(projName)

  - task: DotNetCoreCLI@2
    displayName: "Build the project - $(buildConfiguration)"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration $(buildConfiguration)"
      projects: "$(app)/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Run unit tests - $(buildConfiguration)"
    inputs:
      command: "test"
      arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura%2copencover" /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
      publishTestResults: true
      projects: "testapp/*.csproj"

  - task: SonarCloudAnalyze@1
    displayName: "Run SonarCloud code analysis"

  - task: SonarCloudPublish@1
    displayName: "Publish SonarCloud quality gate results"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"