name: api-ci-cd

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/config-api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  path: apps/config-api/
  azConnection: scDevOpsIntro
  appService: config-api-20671

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        displayName: "Build Api"

        steps:
          - task: UseDotNet@2
            displayName: "Install .NET 6 SDK"
            inputs:
              packageType: "sdk"
              version: "6.x"

          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(path)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(path)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "$(path)/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifact: 'drop'
              publishLocation: 'pipeline'

  - stage: "Deploy"
    displayName: "Deploy"
  
    jobs:
      - deployment: DeployAppService
        displayName: Deploy to prod Appservice
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:                          
              - task: AzureRmWebAppDeployment@4
                displayName: "Azure App Service Deploy: $(appService)"
                inputs:
                  ConnectionType: "AzureRM"
                  azureSubscription: $(azConnection)
                  appType: "webApp"
                  WebAppName: $(appService)
                  packageForLinux: "$(Agent.BuildDirectory)/**/*.zip"