name: ui-build

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/config-ui/*

trigger: none
pr: none

variables:
  app: apps/config-ui/

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: ngbuild

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node 16"

          - script: npm i -g @angular/cli
            displayName: "Install Angular CLI"
            
          - task: Cache@2
            inputs:
                key: '$(System.DefaultWorkingDirectory)/$(app)/package-lock.json'
                path: '$(System.DefaultWorkingDirectory)/$(app)/node_modules'
                cacheHitVar: 'ngCacheRestored'

          - script: npm i            
            displayName: "Install Dependencies"
            workingDirectory: $(app)
            condition: eq(variables['ngCacheRestored'],False)

          - script: ng b -c production
            displayName: "Create Build"
            workingDirectory: $(app)

          - task: PublishPipelineArtifact@1
            inputs:
              targetpath: '$(System.DefaultWorkingDirectory)/$(app)dist/'
              ArtifactName: 'ngapp'